merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:band_id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:band_id>/change/', views.band_update,
         name='band-update'),
    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:listing_id>/', views.listing_detail,
         name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:listing_id>/change/', views.listing_update,
         name='listing-update'),
    path('about-us/', views.about, name='about'),
    path('contact-us/', views.contact, name='contact'),
    path('email-sent/', views.email_sent, name='email-sent')
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2022)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class Listing(models.Model):

    class ListingType(models.TextChoices):
        RECORDS = 'RE'
        CLOTHING = 'CL'
        POSTERS = 'PO'
        MISCELLANEOUS = 'MI'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2022)],
        null=True
    )
    type = models.fields.CharField(choices=ListingType.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'{self.title}'

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000, widget=forms.Textarea)


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        # fields = '__all__'
        exclude = ('active', 'official_homepage')
        widgets = {
            'biography': forms.Textarea
        }


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        exclude = ('sold',)
        widgets = {
            'description': forms.Textarea
        }

merchex/listings/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
from django.shortcuts import redirect
from listings.models import Band, Listing
from listings.forms import ContactUsForm, BandForm, ListingForm


def band_list(request):
    bands = Band.objects.all()
    return render(request,
        "listings/band_list.html",
        context={"bands": bands})

def band_detail(request, band_id):
    band = Band.objects.get(id=band_id)
    return render(request,
        'listings/band_detail.html',
        {'band': band})

def listing_list(request):
    listings = Listing.objects.all()
    return render(request,
        "listings/listing_list.html",
        context={"listings": listings})

def listing_detail(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    return render(request,
        "listings/listing_detail.html",
        {'listing': listing})

def about(request):
    return render(request,
        "listings/about.html")

def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from \
{form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz']
            )
            return redirect('email-sent')

    else:
        form = ContactUsForm()

    return render(request,
        "listings/contact.html",
        {'form': form})

def email_sent(request):
    return render(request,
        "listings/email_sent.html")

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # Créer une nouvelle 'Band' et la sauvegarde dans la db
            band = form.save()
            return redirect('band-detail', band.id)

    else:    
        form = BandForm()

    return render(request,
        "listings/band_create.html",
        {'form': form})

def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm()

    return render(request,
        "listings/listing_create.html",
        {'form': form})

def band_update(request, band_id):
    band = Band.objects.get(id=band_id)
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            form.save()
            return redirect('band-detail', band.id)
    else:
        # On pré-remplit le formulaire avec un groupe existant
        form = BandForm(instance=band)

    return render(request,
        "listings/band_update.html",
        {'form': form})

def listing_update(request, listing_id):
    listing = Listing.objects.get(id=listing_id)

    if request.method == "POST":
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return redirect("listing-detail", listing.id)
    else:
        form = ListingForm(instance=listing)
        
    return render(request,
        "listings/listing_update.html",
        {'form': form})

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>A propos</h1>
<p>Nous adorons merch !</p>

{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Créer un nouveau groupe</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Année de formation : {{ band.year_formed }}</li>
    <li>Actif : {{ band.active|yesno }}</li>
    {% if band.official_homepage %}
    <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
    {% endif %}
    <li>Articles disponibles :
        <ul>
            {% for listing in band.listing_set.all %}
            <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
            {% endfor %}
        </ul>
    </li>
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>
<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% load static %}

{% block content %}

<h1>Groupes</h1>

<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

<ul>
    {% for band in bands %}
        <li>
            <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
            <a href="{% url 'band-update' band.id %}">
                <img class="icon" src="{% static 'listings/img/modifier.png' %}" alt="Modifier"
                title='Modifier'>
            </a>
        </li>
    {% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mettre à jour un groupe</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Merchex</title>
        <link rel="stylesheet" type="text/css" href="{% static 'listings/css/styles.css' %}"/>
    </head>
    <body>

        <nav>
            <a href="{% url 'band-list' %}">Groupes</a>
            <a href="{% url 'listing-list' %}">Listings</a>
            <a href="{% url 'contact' %}">Contact</a>
            <a href="{% url 'about' %}">A propos</a>
        </nav>
        
        {% block content %}{% endblock %}

    </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Contactez nous</h1>
<p>Nous sommes là pour vous aider.</p>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>Confirmation de réception de votre demande de contact.</h2>

<p>Votre email a bien été envoyer.</p>

<p>Nous vous répondrons dans les plus bref délais.</p>

<p>L'équipe de Merchex.</p>

<a href="{% url 'contact' %}">Retour au formulaire de contact</a>

{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Créer un nouvel article</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ listing.title }}</h2>

<ul>
    <li>Type : {{ listing.get_type_display }}</li>
    <li>Année de création : {{ listing.year }}</li>
    <li>Du groupe : {{ listing.band }}</li>
    <li>Vendu : {{ listing.sold|yesno }}</li>
</ul>

<p>{{ listing.description }}</p>

<a href="{% url 'listing-update' listing.id %}">Modifier cet article</a>
<a href="{% url 'listing-list' %}">Retour a tous les listings</a>

{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% load static %}

{% block content %}

<h1>Listings</h1>

<a href="{% url 'listing-create' %}">Créer un nouvel article</a>

<p>Annonces disponnibles :</p>

<ul>
    {% for listing in listings %}
        <li>
            <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }} {{ listing.band }}</a>
            <a href="{% url 'listing-update' listing.id %}">
                <img class="icon" src="{% static 'listings/img/modifier.png' %}" alt="Modifier"
                title='Modifier'>
            </a>
        </li>
    {% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mettre à jour un article</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Listings</h1>
<p>Annonces disponnibles :</p>
<ul>
    {% for listing in listings %}
        <li>{{ listing.title }}</li>
    {% endfor %}
</ul>

{% endblock %}